// Code generated by internal/cmd/typeidgen; DO NOT EDIT.

package crdt

// Stable frame type assignments. Values are part of the v1 wire contract and
// must never be reused for a different payload shape. The source of truth is
// docs/protocol/type-ids.json.
const (
	TypeIDGCounterState   uint64 = 1
	TypeIDGCounterDelta   uint64 = 3
	TypeIDORSetState      uint64 = 2
	TypeIDORSetDelta      uint64 = 4
	TypeIDPNCounterState  uint64 = 5
	TypeIDPNCounterDelta  uint64 = 6
	TypeIDLWWSetState     uint64 = 7
	TypeIDLWWSetDelta     uint64 = 8
	TypeIDLWWMapState     uint64 = 9
	TypeIDLWWMapDelta     uint64 = 10
	TypeIDRGAState        uint64 = 11
	TypeIDRGADelta        uint64 = 12
	TypeIDGSetState       uint64 = 13
	TypeIDGSetDelta       uint64 = 14
	TypeIDMVRegisterState uint64 = 15
	TypeIDMVRegisterDelta uint64 = 16
	TypeIDORTreeState     uint64 = 17
	TypeIDORTreeDelta     uint64 = 18
	TypeIDRGARunState     uint64 = 19
	TypeIDRGARunDelta     uint64 = 20
	TypeIDListRGAState    uint64 = 21
	TypeIDListRGADelta    uint64 = 22
	TypeIDRichTextState   uint64 = 23
	TypeIDRichTextDelta   uint64 = 24
)

var frameTypes = [...]FrameType{
	{StateID: TypeIDGCounterState, DeltaID: TypeIDGCounterDelta},
	{StateID: TypeIDORSetState, DeltaID: TypeIDORSetDelta, UsesHLC: true},
	{StateID: TypeIDPNCounterState, DeltaID: TypeIDPNCounterDelta},
	{StateID: TypeIDLWWSetState, DeltaID: TypeIDLWWSetDelta, UsesHLC: true},
	{StateID: TypeIDLWWMapState, DeltaID: TypeIDLWWMapDelta, UsesHLC: true},
	{StateID: TypeIDRGAState, DeltaID: TypeIDRGADelta, UsesHLC: true},
	{StateID: TypeIDGSetState, DeltaID: TypeIDGSetDelta},
	{StateID: TypeIDMVRegisterState, DeltaID: TypeIDMVRegisterDelta},
	{StateID: TypeIDORTreeState, DeltaID: TypeIDORTreeDelta, UsesHLC: true},
	{StateID: TypeIDRGARunState, DeltaID: TypeIDRGARunDelta, UsesHLC: true},
	{StateID: TypeIDListRGAState, DeltaID: TypeIDListRGADelta, UsesHLC: true},
	{StateID: TypeIDRichTextState, DeltaID: TypeIDRichTextDelta, UsesHLC: true},
}

var experimentalFrameTypes = map[uint64]struct{}{}
