// Generated from docs/protocol/type-ids.json by internal/cmd/typeidgen; DO NOT EDIT.

export const FrameType = {
  GCounterState: 1n,
  GCounterDelta: 3n,
  ORSetState: 2n,
  ORSetDelta: 4n,
  PNCounterState: 5n,
  PNCounterDelta: 6n,
  LWWSetState: 7n,
  LWWSetDelta: 8n,
  LWWMapState: 9n,
  LWWMapDelta: 10n,
  RGAState: 11n,
  RGADelta: 12n,
  GSetState: 13n,
  GSetDelta: 14n,
  MVRegisterState: 15n,
  MVRegisterDelta: 16n,
  ORTreeState: 17n,
  ORTreeDelta: 18n,
  RGARunState: 19n,
  RGARunDelta: 20n,
  ListRGAState: 21n,
  ListRGADelta: 22n,
  RichTextState: 23n,
  RichTextDelta: 24n,
} as const;

export const FrameSemanticsVersion = {
  GCounter: 1n,
  ORSet: 1n,
  PNCounter: 1n,
  LWWSet: 1n,
  LWWMap: 1n,
  RGA: 1n,
  GSet: 1n,
  MVRegister: 1n,
  ORTree: 1n,
  RGARun: 2n,
  ListRGA: 1n,
  RichText: 1n,
} as const;
