package durable

import (
	"crypto/sha256"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/DarkInno/crdt"
	frame "github.com/DarkInno/crdt/encoding"
)

// merkleLeafKey is the canonical, unambiguous HLC identity for an event. HLC
// identities are generated by one relay log, so a tag identifies at most one
// committed event inside one manifest-bound group.
func merkleLeafKey(tag crdt.Tag) string {
	return string(frame.AppendTag(nil, tag))
}

// merkleLeafValue is deliberately independent of a relay sequence. Sequence
// orders one relay's live stream, while the Merkle commitment is over the
// immutable HLC identity and canonical change envelope.
func merkleLeafValue(event Event) ([]byte, error) {
	if !validMerkleHLC(event.HLC, frame.DefaultLimits().MaxStringBytes) {
		return nil, errInvalidWire
	}
	change, err := marshalChange(event.Change)
	if err != nil {
		return nil, err
	}
	encoded := frame.AppendTag(nil, event.HLC)
	return append(encoded, change...), nil
}

func merkleLeafForEvent(event Event) (MerkleLeaf, error) {
	value, err := merkleLeafValue(event)
	if err != nil {
		return MerkleLeaf{}, err
	}
	return MerkleLeaf{HLC: event.HLC, Digest: sha256.Sum256(value)}, nil
}

func merkleLeafBytes(leaf MerkleLeaf) uint64 {
	tagBytes := frame.TagSize(leaf.HLC)
	if tagBytes < 0 {
		return 0
	}
	return uint64(tagBytes) + sha256.Size
}

// maxMerkleEventOverhead reserves the largest v3-only envelope portion before
// an accepted durable change. Keeping that reserve at append time ensures a
// later HLC/Merkle replay cannot contain a valid v1 change that exceeds the
// receiver's negotiated whole-message bound after its relay HLC is attached.
func maxMerkleEventOverhead(maxReplicaBytes int) int {
	if maxReplicaBytes <= 0 || maxReplicaBytes > frame.DefaultLimits().MaxStringBytes {
		return 0
	}
	return 1 + frame.UvarintSize(^uint64(0)) + frame.UvarintSize(uint64(maxReplicaBytes)) + maxReplicaBytes + 2*frame.UvarintSize(^uint64(0))
}

func validMerkleHLC(tag crdt.Tag, maxReplicaBytes int) bool {
	return maxReplicaBytes > 0 && tag.Valid() && utf8.ValidString(tag.ReplicaID) && strings.TrimSpace(tag.ReplicaID) != "" && len(tag.ReplicaID) <= maxReplicaBytes
}

func validateMerkleLeaves(leaves []MerkleLeaf, maxLeaves, maxBytes uint64, maxReplicaBytes int) error {
	if maxLeaves == 0 || maxBytes == 0 || uint64(len(leaves)) > maxLeaves {
		return errInvalidWire
	}
	var usedBytes uint64
	var previous crdt.Tag
	for index, leaf := range leaves {
		if !validMerkleHLC(leaf.HLC, maxReplicaBytes) || (index > 0 && previous.Compare(leaf.HLC) >= 0) || merkleLeafBytes(leaf) > maxBytes-usedBytes {
			return errInvalidWire
		}
		usedBytes += merkleLeafBytes(leaf)
		previous = leaf.HLC
	}
	return nil
}

func sortMerkleLeaves(leaves []MerkleLeaf) {
	sort.Slice(leaves, func(left, right int) bool {
		return leaves[left].HLC.Compare(leaves[right].HLC) < 0
	})
}

func relayHLCState(data []byte, replicaID string, maxReplicaBytes int) (crdt.Tag, error) {
	if strings.TrimSpace(replicaID) == "" || len(replicaID) > maxReplicaBytes {
		return crdt.Tag{}, ErrCorruptStore
	}
	if len(data) == 0 {
		return crdt.Tag{ReplicaID: replicaID}, nil
	}
	tag, position, ok := frame.ReadTag(data, 0, maxReplicaBytes)
	if !ok || position != len(data) || tag.ReplicaID != replicaID || !validMerkleHLC(tag, maxReplicaBytes) {
		return crdt.Tag{}, ErrCorruptStore
	}
	return tag, nil
}

func encodeRelayHLCState(tag crdt.Tag) []byte { return frame.AppendTag(nil, tag) }

func validateMerkleIdentityRequest(identities []crdt.Tag, maxLeaves, maxBytes uint64, maxReplicaBytes int) error {
	if maxLeaves == 0 || maxBytes == 0 || uint64(len(identities)) > maxLeaves {
		return errInvalidWire
	}
	var usedBytes uint64
	var previous crdt.Tag
	for index, identity := range identities {
		tagBytes := frame.TagSize(identity)
		if tagBytes < 0 {
			return errInvalidWire
		}
		identityBytes := uint64(tagBytes)
		if !validMerkleHLC(identity, maxReplicaBytes) || (index > 0 && previous.Compare(identity) >= 0) || identityBytes > maxBytes-usedBytes {
			return errInvalidWire
		}
		usedBytes += identityBytes
		previous = identity
	}
	return nil
}
