// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: extensions/relay.proto

package extensions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SyncMessage_Hello
	//	*SyncMessage_Change
	Payload       isSyncMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessage) Reset() {
	*x = SyncMessage{}
	mi := &file_extensions_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessage) ProtoMessage() {}

func (x *SyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessage.ProtoReflect.Descriptor instead.
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return file_extensions_relay_proto_rawDescGZIP(), []int{0}
}

func (x *SyncMessage) GetPayload() isSyncMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncMessage) GetHello() []byte {
	if x != nil {
		if x, ok := x.Payload.(*SyncMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *SyncMessage) GetChange() []byte {
	if x != nil {
		if x, ok := x.Payload.(*SyncMessage_Change); ok {
			return x.Change
		}
	}
	return nil
}

type isSyncMessage_Payload interface {
	isSyncMessage_Payload()
}

type SyncMessage_Hello struct {
	Hello []byte `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type SyncMessage_Change struct {
	Change []byte `protobuf:"bytes,2,opt,name=change,proto3,oneof"`
}

func (*SyncMessage_Hello) isSyncMessage_Payload() {}

func (*SyncMessage_Change) isSyncMessage_Payload() {}

var File_extensions_relay_proto protoreflect.FileDescriptor

const file_extensions_relay_proto_rawDesc = "" +
	"\n" +
	"\x16extensions/relay.proto\x12\x1bdarkinno.crdt.extensions.v1\"J\n" +
	"\vSyncMessage\x12\x16\n" +
	"\x05hello\x18\x01 \x01(\fH\x00R\x05hello\x12\x18\n" +
	"\x06change\x18\x02 \x01(\fH\x00R\x06changeB\t\n" +
	"\apayload2g\n" +
	"\x05Relay\x12^\n" +
	"\x04Sync\x12(.darkinno.crdt.extensions.v1.SyncMessage\x1a(.darkinno.crdt.extensions.v1.SyncMessage(\x010\x01B0Z.github.com/im10furry/crdt/extensions;extensionsb\x06proto3"

var (
	file_extensions_relay_proto_rawDescOnce sync.Once
	file_extensions_relay_proto_rawDescData []byte
)

func file_extensions_relay_proto_rawDescGZIP() []byte {
	file_extensions_relay_proto_rawDescOnce.Do(func() {
		file_extensions_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extensions_relay_proto_rawDesc), len(file_extensions_relay_proto_rawDesc)))
	})
	return file_extensions_relay_proto_rawDescData
}

var file_extensions_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_extensions_relay_proto_goTypes = []any{
	(*SyncMessage)(nil), // 0: darkinno.crdt.extensions.v1.SyncMessage
}
var file_extensions_relay_proto_depIdxs = []int32{
	0, // 0: darkinno.crdt.extensions.v1.Relay.Sync:input_type -> darkinno.crdt.extensions.v1.SyncMessage
	0, // 1: darkinno.crdt.extensions.v1.Relay.Sync:output_type -> darkinno.crdt.extensions.v1.SyncMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extensions_relay_proto_init() }
func file_extensions_relay_proto_init() {
	if File_extensions_relay_proto != nil {
		return
	}
	file_extensions_relay_proto_msgTypes[0].OneofWrappers = []any{
		(*SyncMessage_Hello)(nil),
		(*SyncMessage_Change)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extensions_relay_proto_rawDesc), len(file_extensions_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extensions_relay_proto_goTypes,
		DependencyIndexes: file_extensions_relay_proto_depIdxs,
		MessageInfos:      file_extensions_relay_proto_msgTypes,
	}.Build()
	File_extensions_relay_proto = out.File
	file_extensions_relay_proto_goTypes = nil
	file_extensions_relay_proto_depIdxs = nil
}
