package extensions

import (
	"bytes"
	"context"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/coder/websocket"
)

// This is a real Yjs v1 update generated by Y.encodeStateAsUpdate after
// inserting "hello" in Y.Text("shared"). The client ID is intentionally
// fixed in this vector; Yjs client IDs are part of the update payload.
var yjsHelloUpdate = []byte{1, 1, 191, 253, 254, 15, 0, 4, 1, 6, 115, 104, 97, 114, 101, 100, 5, 104, 101, 108, 108, 111, 0}

func TestYJSHandlerBootstrapsAndRelaysYProtocolUpdates(t *testing.T) {
	server, room := newYJSTestServer(t)
	writer := newYJSTestClient(t, server.URL, "writer")
	defer writer.CloseNow()
	if data := readYJSMessage(t, writer); !bytes.Equal(data, marshalYJSSync(yjsWireSyncStep2, yjsEmptyUpdate)) {
		t.Fatalf("writer bootstrap = %x", data)
	}
	observer := newYJSTestClient(t, server.URL, "observer")
	defer observer.CloseNow()
	if data := readYJSMessage(t, observer); !bytes.Equal(data, marshalYJSSync(yjsWireSyncStep2, yjsEmptyUpdate)) {
		t.Fatalf("observer bootstrap = %x", data)
	}

	if err := writer.Write(context.Background(), websocket.MessageBinary, marshalYJSSync(yjsWireUpdate, yjsHelloUpdate)); err != nil {
		t.Fatal(err)
	}
	want := marshalYJSSync(yjsWireUpdate, yjsHelloUpdate)
	if data := readYJSMessage(t, writer); !bytes.Equal(data, want) {
		t.Fatalf("writer echo = %x, want %x", data, want)
	}
	if data := readYJSMessage(t, observer); !bytes.Equal(data, want) {
		t.Fatalf("observer update = %x, want %x", data, want)
	}

	late := newYJSTestClient(t, server.URL, "late")
	defer late.CloseNow()
	if data := readYJSMessage(t, late); !bytes.Equal(data, marshalYJSSync(yjsWireSyncStep2, yjsEmptyUpdate)) {
		t.Fatalf("late step 2 = %x", data)
	}
	if data := readYJSMessage(t, late); !bytes.Equal(data, want) {
		t.Fatalf("late bootstrap update = %x, want %x", data, want)
	}

	if !room.appendUpdate(yjsHelloUpdate) { // Exact retries remain live but do not consume history.
		t.Fatal("duplicate update was rejected")
	}
	room.mu.Lock()
	updates, history := len(room.updates), room.history
	room.mu.Unlock()
	if updates != 1 || history != len(yjsHelloUpdate) {
		t.Fatalf("duplicate history = updates=%d bytes=%d", updates, history)
	}
}

func TestYJSHandlerAwarenessOwnershipAndDisconnect(t *testing.T) {
	server, _ := newYJSTestServer(t)
	owner := newYJSTestClient(t, server.URL, "owner")
	defer owner.CloseNow()
	_ = readYJSMessage(t, owner)
	observer := newYJSTestClient(t, server.URL, "observer")
	defer observer.CloseNow()
	_ = readYJSMessage(t, observer)

	initial := marshalYJSAwareness([]yjsAwarenessEntry{{clientID: 42, clock: 1, state: []byte(`{"user":"owner"}`)}})
	if err := owner.Write(context.Background(), websocket.MessageBinary, initial); err != nil {
		t.Fatal(err)
	}
	_ = readYJSMessage(t, owner)
	if data := readYJSMessage(t, observer); !bytes.Equal(data, initial) {
		t.Fatalf("awareness relay = %x, want %x", data, initial)
	}

	// The authenticated connection, rather than the client-selected ID, owns
	// its active awareness record. A second peer cannot claim it.
	forged := marshalYJSAwareness([]yjsAwarenessEntry{{clientID: 42, clock: 2, state: []byte(`{"user":"forged"}`)}})
	if err := observer.Write(context.Background(), websocket.MessageBinary, forged); err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	if _, _, err := observer.Read(ctx); err == nil {
		t.Fatal("forged awareness owner remained connected")
	}

	if err := owner.Close(websocket.StatusNormalClosure, "done"); err != nil {
		t.Fatal(err)
	}
	// The observer was intentionally closed by the forged message, so attach a
	// fresh authorized receiver to verify that offline state is not replayed.
	late := newYJSTestClient(t, server.URL, "late")
	defer late.CloseNow()
	_ = readYJSMessage(t, late)
	ctx, cancel = context.WithTimeout(context.Background(), 50*time.Millisecond)
	defer cancel()
	if _, _, err := late.Read(ctx); !errors.Is(err, context.DeadlineExceeded) {
		t.Fatalf("disconnected awareness was replayed: %v", err)
	}
}

func TestYJSWireRejectsMalformedAndOverlargeInputBeforeMutation(t *testing.T) {
	if _, err := unmarshalYJSMessages([]byte{0, 0}, 1024, 8); !errors.Is(err, errInvalidWireMessage) {
		t.Fatalf("truncated sync error = %v", err)
	}
	// A non-canonical varuint must not be accepted as a room/message type.
	if _, err := unmarshalYJSMessages([]byte{0x80, 0x00, 0x00}, 1024, 8); !errors.Is(err, errInvalidWireMessage) {
		t.Fatalf("non-canonical type error = %v", err)
	}
	tooMany := marshalYJSAwareness([]yjsAwarenessEntry{
		{clientID: 1, clock: 1, state: []byte(`{}`)},
		{clientID: 2, clock: 1, state: []byte(`{}`)},
	})
	if _, err := unmarshalYJSMessages(tooMany, 1024, 1); !errors.Is(err, errInvalidWireMessage) {
		t.Fatalf("too-many awareness clients error = %v", err)
	}
	if _, err := NewYJSRoom(YJSRoomConfig{Name: "notes", MaxUpdateBytes: 64, MaxHistoryBytes: 63, MaxUpdates: 1}); !errors.Is(err, ErrInvalidConfig) {
		t.Fatalf("invalid room limits error = %v", err)
	}
	room, err := NewYJSRoom(YJSRoomConfig{Name: "bounded", MaxUpdateBytes: 64, MaxHistoryBytes: 64, MaxUpdates: 1})
	if err != nil {
		t.Fatal(err)
	}
	if !room.applyAwareness(Peer{ID: "one"}, []yjsAwarenessEntry{{clientID: 1, clock: 1, state: []byte(`{}`)}}, 1) {
		t.Fatal("first awareness state was rejected")
	}
	if room.applyAwareness(Peer{ID: "two"}, []yjsAwarenessEntry{{clientID: 2, clock: 1, state: []byte(`{}`)}}, 1) {
		t.Fatal("awareness state above the room cap was accepted")
	}
}

func TestYJSConcurrentPublishSimulationRetainsEveryDistinctOpaqueUpdate(t *testing.T) {
	server, room := newYJSTestServer(t)
	observer := newYJSTestClient(t, server.URL, "observer")
	defer observer.CloseNow()
	_ = readYJSMessage(t, observer)
	const writers = 8
	clients := make([]*websocket.Conn, writers)
	for index := range clients {
		clients[index] = newYJSTestClient(t, server.URL, string(rune('a'+index)))
		defer clients[index].CloseNow()
		_ = readYJSMessage(t, clients[index])
	}
	updates := make([][]byte, writers)
	for index := range updates {
		updates[index] = append([]byte(nil), yjsHelloUpdate...)
		updates[index][2] = byte(0xb0 + index) // distinct, still canonical Yjs client-ID varuint bytes
	}
	var publish sync.WaitGroup
	for index, client := range clients {
		publish.Add(1)
		go func(client *websocket.Conn, update []byte) {
			defer publish.Done()
			if err := client.Write(context.Background(), websocket.MessageBinary, marshalYJSSync(yjsWireUpdate, update)); err != nil {
				t.Errorf("publish: %v", err)
			}
		}(client, updates[index])
	}
	publish.Wait()
	received := make(map[string]struct{}, writers)
	for index := 0; index < writers; index++ {
		incoming, err := unmarshalYJSMessages(readYJSMessage(t, observer), 4096, 16)
		if err != nil || len(incoming) != 1 || incoming[0].kind != YJSUpdate {
			t.Fatalf("observer message %d = %#v, %v", index, incoming, err)
		}
		received[string(incoming[0].payload)] = struct{}{}
	}
	if len(received) != writers {
		t.Fatalf("received %d distinct updates, want %d", len(received), writers)
	}
	room.mu.Lock()
	retained := len(room.updates)
	room.mu.Unlock()
	if retained != writers {
		t.Fatalf("retained updates = %d, want %d", retained, writers)
	}
}

func FuzzUnmarshalYJSMessages(f *testing.F) {
	f.Add([]byte{0, 0, 1, 0})
	f.Add(marshalYJSSync(yjsWireUpdate, yjsHelloUpdate))
	f.Add(marshalYJSAwareness([]yjsAwarenessEntry{{clientID: 1, clock: 1, state: []byte(`{}`)}}))
	f.Fuzz(func(t *testing.T, data []byte) {
		_, _ = unmarshalYJSMessages(data, 4096, 16)
	})
}

func BenchmarkYJSWireDecodeAndAdmission(b *testing.B) {
	room, err := NewYJSRoom(YJSRoomConfig{Name: "bench", MaxUpdateBytes: 4096, MaxHistoryBytes: 4096, MaxUpdates: 1})
	if err != nil {
		b.Fatal(err)
	}
	message := marshalYJSSync(yjsWireUpdate, yjsHelloUpdate)
	b.ReportAllocs()
	b.ResetTimer()
	for index := 0; index < b.N; index++ {
		incoming, err := unmarshalYJSMessages(message, 4096, 16)
		if err != nil {
			b.Fatal(err)
		}
		if !room.appendUpdate(incoming[0].payload) {
			b.Fatal("admission failed")
		}
	}
}

func newYJSTestServer(t testing.TB) (*httptest.Server, *YJSRoom) {
	t.Helper()
	room, err := NewYJSRoom(YJSRoomConfig{Name: "notes", MaxUpdateBytes: 4096, MaxHistoryBytes: 32 << 10, MaxUpdates: 16})
	if err != nil {
		t.Fatal(err)
	}
	handler, err := NewYJSHandler(YJSConfig{
		Rooms: []*YJSRoom{room},
		Authenticate: func(request *http.Request) (Peer, error) {
			const prefix = "Bearer "
			value := request.Header.Get("Authorization")
			if !strings.HasPrefix(value, prefix) {
				return Peer{}, ErrUnauthorized
			}
			return Peer{ID: strings.TrimPrefix(value, prefix)}, nil
		},
		Authorize: func(Peer, string, YJSMessageKind) error { return nil },
		AuthorizeSubscription: func(peer Peer, _ string) error {
			if peer.ID == "denied" {
				return ErrUnauthorized
			}
			return nil
		},
		MaxMessageBytes:     4096,
		MaxQueuedMessages:   16,
		MaxQueuedBytes:      4096,
		MaxAwarenessClients: 16,
	})
	if err != nil {
		t.Fatal(err)
	}
	server := httptest.NewServer(handler)
	t.Cleanup(server.Close)
	return server, room
}

func newYJSTestClient(t testing.TB, serverURL, identity string) *websocket.Conn {
	t.Helper()
	endpoint := "ws" + strings.TrimPrefix(serverURL, "http") + "/notes"
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	conn, response, err := websocket.Dial(ctx, endpoint, &websocket.DialOptions{HTTPHeader: http.Header{"Authorization": []string{"Bearer " + identity}}})
	if err != nil {
		if response != nil {
			t.Fatalf("dial %s: %v (status=%d)", identity, err, response.StatusCode)
		}
		t.Fatalf("dial %s: %v", identity, err)
	}
	return conn
}

func readYJSMessage(t testing.TB, conn *websocket.Conn) []byte {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	messageType, data, err := conn.Read(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if messageType != websocket.MessageBinary {
		t.Fatalf("message type = %v", messageType)
	}
	return data
}
