package extensions

import (
	"bytes"
	"context"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/coder/websocket"
)

// This is a real Yjs v1 update generated by Y.encodeStateAsUpdate after
// inserting "hello" in Y.Text("shared"). The client ID is intentionally
// fixed in this vector; Yjs client IDs are part of the update payload.
var yjsHelloUpdate = []byte{1, 1, 191, 253, 254, 15, 0, 4, 1, 6, 115, 104, 97, 114, 101, 100, 5, 104, 101, 108, 108, 111, 0}

func TestYJSHandlerBootstrapsAndRelaysYProtocolUpdates(t *testing.T) {
	server, room := newYJSTestServer(t)
	writer := newYJSTestClient(t, server.URL, "writer")
	defer func() { _ = writer.CloseNow() }()
	if data := readYJSMessage(t, writer); !bytes.Equal(data, marshalYJSSync(yjsWireSyncStep2, yjsEmptyUpdate)) {
		t.Fatalf("writer bootstrap = %x", data)
	}
	observer := newYJSTestClient(t, server.URL, "observer")
	defer func() { _ = observer.CloseNow() }()
	if data := readYJSMessage(t, observer); !bytes.Equal(data, marshalYJSSync(yjsWireSyncStep2, yjsEmptyUpdate)) {
		t.Fatalf("observer bootstrap = %x", data)
	}

	if err := writer.Write(context.Background(), websocket.MessageBinary, marshalYJSSync(yjsWireUpdate, yjsHelloUpdate)); err != nil {
		t.Fatal(err)
	}
	want := marshalYJSSync(yjsWireUpdate, yjsHelloUpdate)
	if data := readYJSMessage(t, writer); !bytes.Equal(data, want) {
		t.Fatalf("writer echo = %x, want %x", data, want)
	}
	if data := readYJSMessage(t, observer); !bytes.Equal(data, want) {
		t.Fatalf("observer update = %x, want %x", data, want)
	}

	late := newYJSTestClient(t, server.URL, "late")
	defer func() { _ = late.CloseNow() }()
	if data := readYJSMessage(t, late); !bytes.Equal(data, marshalYJSSync(yjsWireSyncStep2, yjsEmptyUpdate)) {
		t.Fatalf("late step 2 = %x", data)
	}
	if data := readYJSMessage(t, late); !bytes.Equal(data, want) {
		t.Fatalf("late bootstrap update = %x, want %x", data, want)
	}

	if !room.appendUpdate(yjsHelloUpdate) { // Exact retries remain live but do not consume history.
		t.Fatal("duplicate update was rejected")
	}
	room.mu.Lock()
	updates, history := len(room.updates), room.history
	room.mu.Unlock()
	if updates != 1 || history != len(yjsHelloUpdate) {
		t.Fatalf("duplicate history = updates=%d bytes=%d", updates, history)
	}
}

func TestYJSHandlerAwarenessOwnershipAndDisconnect(t *testing.T) {
	server, room := newYJSTestServer(t)
	owner := newYJSTestClient(t, server.URL, "owner")
	defer func() { _ = owner.CloseNow() }()
	_ = readYJSMessage(t, owner)
	observer := newYJSTestClient(t, server.URL, "observer")
	defer func() { _ = observer.CloseNow() }()
	_ = readYJSMessage(t, observer)

	initial := marshalYJSAwareness([]yjsAwarenessEntry{{clientID: 42, clock: 1, state: []byte(`{"user":"owner"}`)}})
	if err := owner.Write(context.Background(), websocket.MessageBinary, initial); err != nil {
		t.Fatal(err)
	}
	_ = readYJSMessage(t, owner)
	if data := readYJSMessage(t, observer); !bytes.Equal(data, initial) {
		t.Fatalf("awareness relay = %x, want %x", data, initial)
	}

	// The authenticated connection, rather than the client-selected ID, owns
	// its active awareness record. A second peer cannot claim it.
	forged := marshalYJSAwareness([]yjsAwarenessEntry{{clientID: 42, clock: 2, state: []byte(`{"user":"forged"}`)}})
	if err := observer.Write(context.Background(), websocket.MessageBinary, forged); err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	if _, _, err := observer.Read(ctx); err == nil {
		t.Fatal("forged awareness owner remained connected")
	}

	if err := owner.Close(websocket.StatusNormalClosure, "done"); err != nil {
		t.Fatal(err)
	}
	waitForYJSAwarenessRemoval(t, room, 42)
	// The observer was intentionally closed by the forged message, so attach a
	// fresh authorized receiver to verify that offline state is not replayed.
	late := newYJSTestClient(t, server.URL, "late")
	defer func() { _ = late.CloseNow() }()
	_ = readYJSMessage(t, late)
	ctx, cancel = context.WithTimeout(context.Background(), 50*time.Millisecond)
	defer cancel()
	if _, _, err := late.Read(ctx); !errors.Is(err, context.DeadlineExceeded) {
		t.Fatalf("disconnected awareness was replayed: %v", err)
	}
}

func TestYJSWireRejectsMalformedAndOverlargeInputBeforeMutation(t *testing.T) {
	if _, err := unmarshalYJSMessages([]byte{0, 0}, 1024, 8); !errors.Is(err, errInvalidWireMessage) {
		t.Fatalf("truncated sync error = %v", err)
	}
	// A non-canonical varuint must not be accepted as a room/message type.
	if _, err := unmarshalYJSMessages([]byte{0x80, 0x00, 0x00}, 1024, 8); !errors.Is(err, errInvalidWireMessage) {
		t.Fatalf("non-canonical type error = %v", err)
	}
	tooMany := marshalYJSAwareness([]yjsAwarenessEntry{
		{clientID: 1, clock: 1, state: []byte(`{}`)},
		{clientID: 2, clock: 1, state: []byte(`{}`)},
	})
	if _, err := unmarshalYJSMessages(tooMany, 1024, 1); !errors.Is(err, errInvalidWireMessage) {
		t.Fatalf("too-many awareness clients error = %v", err)
	}
	if _, err := NewYJSRoom(YJSRoomConfig{Name: "notes", MaxUpdateBytes: 64, MaxHistoryBytes: 63, MaxUpdates: 1}); !errors.Is(err, ErrInvalidConfig) {
		t.Fatalf("invalid room limits error = %v", err)
	}
	room, err := NewYJSRoom(YJSRoomConfig{Name: "bounded", MaxUpdateBytes: 64, MaxHistoryBytes: 64, MaxUpdates: 1})
	if err != nil {
		t.Fatal(err)
	}
	if !room.applyAwareness(Peer{ID: "one"}, []yjsAwarenessEntry{{clientID: 1, clock: 1, state: []byte(`{}`)}}, 1) {
		t.Fatal("first awareness state was rejected")
	}
	if room.applyAwareness(Peer{ID: "two"}, []yjsAwarenessEntry{{clientID: 2, clock: 1, state: []byte(`{}`)}}, 1) {
		t.Fatal("awareness state above the room cap was accepted")
	}
}

func TestYJSWireLimitsAndAwarenessSnapshots(t *testing.T) {
	if _, _, ok := yjsReadBytes([]byte{0x01, 0x7f}, 0, 1); !ok {
		t.Fatal("bounded byte payload was rejected")
	}
	if _, _, ok := yjsReadBytes([]byte{0x02, 0x7f}, 0, 1); ok {
		t.Fatal("payload above configured limit was accepted")
	}
	if _, _, ok := yjsReadBytes([]byte{0x80, 0x00}, 0, 1); ok {
		t.Fatal("non-canonical byte length was accepted")
	}
	if _, _, ok := yjsReadBytes([]byte{0x01}, 0, -1); ok {
		t.Fatal("negative byte limit was accepted")
	}
	tooMany := marshalYJSAwareness([]yjsAwarenessEntry{{clientID: 1, clock: 1, state: []byte(`{}`)}})
	if _, ok := unmarshalYJSAwareness(tooMany[2:], 0); ok {
		t.Fatal("awareness entry exceeded zero-client limit")
	}
	if _, ok := unmarshalYJSAwareness(tooMany[2:], maxYJSAwarenessClients+1); ok {
		t.Fatal("unbounded awareness limit was accepted")
	}

	room, err := NewYJSRoom(YJSRoomConfig{Name: "snapshots", MaxUpdateBytes: 64, MaxHistoryBytes: 128, MaxUpdates: 2})
	if err != nil {
		t.Fatal(err)
	}
	if room.Name() != "snapshots" {
		t.Fatalf("room name = %q", room.Name())
	}
	if !room.applyAwareness(Peer{ID: "owner"}, []yjsAwarenessEntry{{clientID: 9, clock: 3, state: []byte(`{"user":"owner"}`)}}, 2) {
		t.Fatal("initial awareness state was rejected")
	}
	messages := room.awarenessMessages()
	if len(messages) != 1 {
		t.Fatalf("awareness snapshot count = %d", len(messages))
	}
	incoming, err := unmarshalYJSMessages(messages[0], 64, 2)
	if err != nil || len(incoming) != 1 || incoming[0].kind != YJSAwareness {
		t.Fatalf("awareness snapshot = %#v, %v", incoming, err)
	}
	subscriber := &yjsSubscriber{}
	room.addAndBootstrap(subscriber, Peer{ID: "owner"})
	room.remove(subscriber, Peer{ID: "owner"})
	if got := room.awarenessMessages(); len(got) != 0 {
		t.Fatalf("removed awareness snapshot count = %d", len(got))
	}
}

func TestYJSHandlerConfigurationAndRoutingBoundaries(t *testing.T) {
	var emptyRoom *YJSRoom
	if emptyRoom.Name() != "" {
		t.Fatal("nil room reported a name")
	}
	if uvarintSize(128) != 2 {
		t.Fatalf("two-byte varuint size = %d", uvarintSize(128))
	}
	room, err := NewYJSRoom(YJSRoomConfig{Name: "notes", MaxUpdateBytes: 1024, MaxHistoryBytes: 1024, MaxUpdates: 1})
	if err != nil {
		t.Fatal(err)
	}
	config := YJSConfig{
		Rooms:                 []*YJSRoom{room},
		Authenticate:          func(*http.Request) (Peer, error) { return Peer{ID: "peer"}, nil },
		Authorize:             func(Peer, string, YJSMessageKind) error { return nil },
		AuthorizeSubscription: func(Peer, string) error { return nil },
		MaxMessageBytes:       1024,
		MaxQueuedMessages:     1,
		MaxQueuedBytes:        1024,
		MaxAwarenessClients:   1,
	}
	handler, err := NewYJSHandler(config)
	if err != nil {
		t.Fatal(err)
	}
	for _, requestPath := range []string{"/notes/extra", "/", "/missing", "/%2Fnotes"} {
		if resolved, ok := handler.roomForPath(requestPath); ok || resolved != nil {
			t.Fatalf("invalid room path %q resolved", requestPath)
		}
	}
	if resolved, ok := handler.roomForPath("/notes"); !ok || resolved != room {
		t.Fatalf("configured room path = %v, %v", resolved, ok)
	}
	config.MaxMessageBytes = maxYJSMessageBytes + 1
	if _, err := NewYJSHandler(config); !errors.Is(err, ErrInvalidConfig) {
		t.Fatalf("oversized message limit error = %v", err)
	}
	config.MaxMessageBytes = 1024
	config.MaxAwarenessClients = -1
	if _, err := NewYJSHandler(config); !errors.Is(err, ErrInvalidConfig) {
		t.Fatalf("negative awareness limit error = %v", err)
	}
	config.MaxAwarenessClients = 1
	config.StoreTimeout = -time.Second
	if _, err := NewYJSHandler(config); !errors.Is(err, ErrInvalidConfig) {
		t.Fatalf("negative store timeout error = %v", err)
	}
	config.StoreTimeout = 0
	config.Rooms = nil
	if _, err := NewYJSHandler(config); !errors.Is(err, ErrInvalidConfig) {
		t.Fatalf("empty rooms error = %v", err)
	}
	config.Rooms = []*YJSRoom{room, room}
	if _, err := NewYJSHandler(config); !errors.Is(err, ErrInvalidConfig) {
		t.Fatalf("duplicate room error = %v", err)
	}

	store := &testSemanticYJSStore{vector: []byte{0}, delta: yjsHelloUpdate}
	document := testYJSDocument()
	firstStoreRoom, err := NewYJSRoom(YJSRoomConfig{
		Name:                "notes-a",
		MaxUpdateBytes:      512,
		MaxStateVectorBytes: 64,
		MaxSyncBytes:        512,
		Store:               store,
		Document:            document,
	})
	if err != nil {
		t.Fatal(err)
	}
	secondStoreRoom, err := NewYJSRoom(YJSRoomConfig{
		Name:                "notes-b",
		MaxUpdateBytes:      512,
		MaxStateVectorBytes: 64,
		MaxSyncBytes:        512,
		Store:               store,
		Document:            document,
	})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := NewYJSHandler(YJSConfig{
		Rooms:                 []*YJSRoom{firstStoreRoom, secondStoreRoom},
		Authenticate:          func(*http.Request) (Peer, error) { return Peer{ID: "peer"}, nil },
		Authorize:             func(Peer, string, YJSMessageKind) error { return nil },
		AuthorizeSubscription: func(Peer, string) error { return nil },
		MaxMessageBytes:       512 + maxYJSWireOverhead,
		MaxQueuedMessages:     1,
		MaxQueuedBytes:        512 + maxYJSWireOverhead,
		MaxAwarenessClients:   1,
	}); !errors.Is(err, ErrInvalidConfig) {
		t.Fatalf("duplicate durable document error = %v", err)
	}
}

func TestYJSRoomCapacityAndSubscriberBackpressure(t *testing.T) {
	server, _ := newYJSTestServer(t)
	client := newYJSTestClient(t, server.URL, "queued")
	defer func() { _ = client.CloseNow() }()
	_ = readYJSMessage(t, client)

	room, err := NewYJSRoom(YJSRoomConfig{Name: "capacity", MaxUpdateBytes: 4, MaxHistoryBytes: 4, MaxUpdates: 1})
	if err != nil {
		t.Fatal(err)
	}
	if room.appendUpdate(nil) || room.appendUpdate([]byte("oversize")) {
		t.Fatal("invalid update was accepted")
	}
	if !room.appendUpdate([]byte("one")) {
		t.Fatal("first update was rejected")
	}
	if room.appendUpdate([]byte("two")) {
		t.Fatal("update above room capacity was accepted")
	}
	if !room.applyAwareness(Peer{ID: "owner"}, []yjsAwarenessEntry{{clientID: 1, clock: 3, state: []byte(`{}`)}}, 1) {
		t.Fatal("initial awareness was rejected")
	}
	if !room.applyAwareness(Peer{ID: "owner"}, []yjsAwarenessEntry{{clientID: 1, clock: 2, state: []byte(`{}`)}}, 1) {
		t.Fatal("older awareness retry was rejected")
	}
	if !room.applyAwareness(Peer{ID: "owner"}, []yjsAwarenessEntry{{clientID: 1, clock: 4, state: []byte("null")}}, 1) {
		t.Fatal("awareness removal was rejected")
	}

	ctx, cancel := context.WithCancel(context.Background())
	subscriber := &yjsSubscriber{context: ctx, cancel: cancel, conn: client, queue: newPeerQueue(1, 32)}
	room.mu.Lock()
	room.peers[subscriber] = Peer{ID: "queued"}
	room.mu.Unlock()
	room.broadcast([]byte("first"))
	room.broadcast([]byte("second"))
	room.mu.Lock()
	remaining := len(room.peers)
	room.mu.Unlock()
	if remaining != 0 {
		t.Fatalf("backpressured subscriber count = %d", remaining)
	}
}

func TestYJSHandlerProtocolControlMessages(t *testing.T) {
	server, _ := newYJSTestServer(t)
	client := newYJSTestClient(t, server.URL, "control")
	defer func() { _ = client.CloseNow() }()
	_ = readYJSMessage(t, client)
	if err := client.Write(context.Background(), websocket.MessageBinary, marshalYJSSync(yjsWireSyncStep1, yjsEmptyUpdate)); err != nil {
		t.Fatal(err)
	}
	if data := readYJSMessage(t, client); !bytes.Equal(data, marshalYJSSync(yjsWireSyncStep2, yjsEmptyUpdate)) {
		t.Fatalf("sync step 1 response = %x", data)
	}
	awareness := marshalYJSAwareness([]yjsAwarenessEntry{{clientID: 7, clock: 1, state: []byte(`{"user":"control"}`)}})
	if err := client.Write(context.Background(), websocket.MessageBinary, awareness); err != nil {
		t.Fatal(err)
	}
	_ = readYJSMessage(t, client)
	if err := client.Write(context.Background(), websocket.MessageBinary, []byte{byte(yjsMessageAwarenessQuery)}); err != nil {
		t.Fatal(err)
	}
	if data := readYJSMessage(t, client); !bytes.Equal(data, awareness) {
		t.Fatalf("awareness query response = %x", data)
	}
}

func TestYJSStoreBackedRoomUsesDurableStateVectorAndDiff(t *testing.T) {
	store := &testSemanticYJSStore{vector: []byte{0}, delta: yjsHelloUpdate}
	document := testYJSDocument()
	room, err := NewYJSRoom(YJSRoomConfig{
		Name:                "notes",
		MaxUpdateBytes:      4096,
		MaxStateVectorBytes: 64,
		MaxSyncBytes:        4096,
		Store:               store,
		Document:            document,
	})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := NewYJSRoom(YJSRoomConfig{Name: "invalid", MaxUpdateBytes: 1024, Store: store, Document: document}); !errors.Is(err, ErrInvalidConfig) {
		t.Fatalf("store room without semantic bounds error = %v", err)
	}
	handler, err := NewYJSHandler(YJSConfig{
		Rooms: []*YJSRoom{room},
		Authenticate: func(request *http.Request) (Peer, error) {
			return Peer{ID: strings.TrimPrefix(request.Header.Get("Authorization"), "Bearer ")}, nil
		},
		Authorize:             func(Peer, string, YJSMessageKind) error { return nil },
		AuthorizeSubscription: func(Peer, string) error { return nil },
		MaxMessageBytes:       4096 + maxYJSWireOverhead,
		MaxQueuedMessages:     16,
		MaxQueuedBytes:        4096 + maxYJSWireOverhead,
		MaxAwarenessClients:   16,
	})
	if err != nil {
		t.Fatal(err)
	}
	server := httptest.NewServer(handler)
	defer server.Close()
	client := newYJSTestClient(t, server.URL, "writer")
	defer func() { _ = client.CloseNow() }()
	if message := readYJSMessage(t, client); !bytes.Equal(message, marshalYJSSync(yjsWireSyncStep1, store.vector)) {
		t.Fatalf("store bootstrap = %x", message)
	}
	remoteVector := []byte{9}
	if err := client.Write(context.Background(), websocket.MessageBinary, marshalYJSSync(yjsWireSyncStep1, remoteVector)); err != nil {
		t.Fatal(err)
	}
	if message := readYJSMessage(t, client); !bytes.Equal(message, marshalYJSSync(yjsWireSyncStep2, store.delta)) {
		t.Fatalf("store diff = %x", message)
	}
	if err := client.Write(context.Background(), websocket.MessageBinary, marshalYJSSync(yjsWireUpdate, yjsHelloUpdate)); err != nil {
		t.Fatal(err)
	}
	if message := readYJSMessage(t, client); !bytes.Equal(message, marshalYJSSync(yjsWireUpdate, yjsHelloUpdate)) {
		t.Fatalf("store broadcast = %x", message)
	}
	store.mu.Lock()
	gotDocument, gotUpdate, gotVector := store.document, store.update, store.remoteVector
	store.mu.Unlock()
	if gotDocument != document || !bytes.Equal(gotUpdate, yjsHelloUpdate) || !bytes.Equal(gotVector, remoteVector) {
		t.Fatalf("store calls document=%#v update=%x vector=%x", gotDocument, gotUpdate, gotVector)
	}
	room.mu.Lock()
	retained := len(room.updates)
	room.mu.Unlock()
	if retained != 0 {
		t.Fatalf("store-backed room retained %d opaque updates", retained)
	}
}

func TestYJSHandlerRejectsHTTPBoundaries(t *testing.T) {
	request := httptest.NewRequest(http.MethodGet, "http://relay.test/notes", nil)
	response := httptest.NewRecorder()
	var unavailable *YJSHandler
	unavailable.ServeHTTP(response, request)
	if response.Code != http.StatusServiceUnavailable {
		t.Fatalf("nil handler status = %d", response.Code)
	}

	room, err := NewYJSRoom(YJSRoomConfig{Name: "notes", MaxUpdateBytes: 1024, MaxHistoryBytes: 1024, MaxUpdates: 1})
	if err != nil {
		t.Fatal(err)
	}
	config := YJSConfig{
		Rooms:                 []*YJSRoom{room},
		Authenticate:          func(*http.Request) (Peer, error) { return Peer{ID: "peer"}, nil },
		Authorize:             func(Peer, string, YJSMessageKind) error { return nil },
		AuthorizeSubscription: func(Peer, string) error { return nil },
		OriginPatterns:        []string{"allowed.test"},
		MaxMessageBytes:       1024,
		MaxQueuedMessages:     1,
		MaxQueuedBytes:        1024,
		MaxAwarenessClients:   1,
	}
	handler, err := NewYJSHandler(config)
	if err != nil {
		t.Fatal(err)
	}
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, httptest.NewRequest(http.MethodGet, "http://relay.test/missing", nil))
	if response.Code != http.StatusNotFound {
		t.Fatalf("unknown room status = %d", response.Code)
	}
	forbidden := httptest.NewRequest(http.MethodGet, "http://relay.test/notes", nil)
	forbidden.Header.Set("Origin", "https://denied.test")
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, forbidden)
	if response.Code != http.StatusForbidden {
		t.Fatalf("origin rejection status = %d", response.Code)
	}
	config.OriginPatterns = nil
	config.Authenticate = func(*http.Request) (Peer, error) { return Peer{}, ErrUnauthorized }
	handler, err = NewYJSHandler(config)
	if err != nil {
		t.Fatal(err)
	}
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusUnauthorized {
		t.Fatalf("authentication rejection status = %d", response.Code)
	}
	config.Authenticate = func(*http.Request) (Peer, error) { return Peer{ID: "peer"}, nil }
	config.AuthorizeSubscription = func(Peer, string) error { return ErrUnauthorized }
	handler, err = NewYJSHandler(config)
	if err != nil {
		t.Fatal(err)
	}
	response = httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusForbidden {
		t.Fatalf("subscription rejection status = %d", response.Code)
	}
}

func TestYJSDecodeRejectsProtocolBoundaries(t *testing.T) {
	for _, data := range [][]byte{
		nil,
		make([]byte, maxYJSMessageBytes+1),
		marshalYJSSync(99, []byte{1}),
		marshalYJSSync(yjsWireUpdate, nil),
		{9},
	} {
		if _, err := unmarshalYJSMessages(data, maxYJSMessageBytes, 1); !errors.Is(err, errInvalidWireMessage) {
			t.Fatalf("decode %x error = %v", data[:min(len(data), 8)], err)
		}
	}
}

func TestYJSConcurrentPublishSimulationRetainsEveryDistinctOpaqueUpdate(t *testing.T) {
	server, room := newYJSTestServer(t)
	observer := newYJSTestClient(t, server.URL, "observer")
	defer func() { _ = observer.CloseNow() }()
	_ = readYJSMessage(t, observer)
	const writers = 8
	clients := make([]*websocket.Conn, writers)
	for index := range clients {
		clients[index] = newYJSTestClient(t, server.URL, string(rune('a'+index)))
		defer func(connection *websocket.Conn) { _ = connection.CloseNow() }(clients[index])
		_ = readYJSMessage(t, clients[index])
	}
	updates := make([][]byte, writers)
	for index := range updates {
		updates[index] = append([]byte(nil), yjsHelloUpdate...)
		updates[index][2] = byte(0xb0 + index) // distinct, still canonical Yjs client-ID varuint bytes
	}
	var publish sync.WaitGroup
	for index, client := range clients {
		publish.Add(1)
		go func(client *websocket.Conn, update []byte) {
			defer publish.Done()
			if err := client.Write(context.Background(), websocket.MessageBinary, marshalYJSSync(yjsWireUpdate, update)); err != nil {
				t.Errorf("publish: %v", err)
			}
		}(client, updates[index])
	}
	publish.Wait()
	received := make(map[string]struct{}, writers)
	for index := 0; index < writers; index++ {
		incoming, err := unmarshalYJSMessages(readYJSMessage(t, observer), 4096, 16)
		if err != nil || len(incoming) != 1 || incoming[0].kind != YJSUpdate {
			t.Fatalf("observer message %d = %#v, %v", index, incoming, err)
		}
		received[string(incoming[0].payload)] = struct{}{}
	}
	if len(received) != writers {
		t.Fatalf("received %d distinct updates, want %d", len(received), writers)
	}
	room.mu.Lock()
	retained := len(room.updates)
	room.mu.Unlock()
	if retained != writers {
		t.Fatalf("retained updates = %d, want %d", retained, writers)
	}
}

func FuzzUnmarshalYJSMessages(f *testing.F) {
	f.Add([]byte{0, 0, 1, 0})
	f.Add(marshalYJSSync(yjsWireUpdate, yjsHelloUpdate))
	f.Add(marshalYJSAwareness([]yjsAwarenessEntry{{clientID: 1, clock: 1, state: []byte(`{}`)}}))
	f.Fuzz(func(t *testing.T, data []byte) {
		_, _ = unmarshalYJSMessages(data, 4096, 16)
	})
}

func BenchmarkYJSWireDecodeAndAdmission(b *testing.B) {
	room, err := NewYJSRoom(YJSRoomConfig{Name: "bench", MaxUpdateBytes: 4096, MaxHistoryBytes: 4096, MaxUpdates: 1})
	if err != nil {
		b.Fatal(err)
	}
	message := marshalYJSSync(yjsWireUpdate, yjsHelloUpdate)
	b.ReportAllocs()
	b.ResetTimer()
	for index := 0; index < b.N; index++ {
		incoming, err := unmarshalYJSMessages(message, 4096, 16)
		if err != nil {
			b.Fatal(err)
		}
		if !room.appendUpdate(incoming[0].payload) {
			b.Fatal("admission failed")
		}
	}
}

func newYJSTestServer(t testing.TB) (*httptest.Server, *YJSRoom) {
	t.Helper()
	room, err := NewYJSRoom(YJSRoomConfig{Name: "notes", MaxUpdateBytes: 4096, MaxHistoryBytes: 32 << 10, MaxUpdates: 16})
	if err != nil {
		t.Fatal(err)
	}
	handler, err := NewYJSHandler(YJSConfig{
		Rooms: []*YJSRoom{room},
		Authenticate: func(request *http.Request) (Peer, error) {
			const prefix = "Bearer "
			value := request.Header.Get("Authorization")
			if !strings.HasPrefix(value, prefix) {
				return Peer{}, ErrUnauthorized
			}
			return Peer{ID: strings.TrimPrefix(value, prefix)}, nil
		},
		Authorize: func(Peer, string, YJSMessageKind) error { return nil },
		AuthorizeSubscription: func(peer Peer, _ string) error {
			if peer.ID == "denied" {
				return ErrUnauthorized
			}
			return nil
		},
		MaxMessageBytes:     4096,
		MaxQueuedMessages:   16,
		MaxQueuedBytes:      4096,
		MaxAwarenessClients: 16,
	})
	if err != nil {
		t.Fatal(err)
	}
	server := httptest.NewServer(handler)
	t.Cleanup(server.Close)
	return server, room
}

func newYJSTestClient(t testing.TB, serverURL, identity string) *websocket.Conn {
	t.Helper()
	endpoint := "ws" + strings.TrimPrefix(serverURL, "http") + "/notes"
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	conn, response, err := websocket.Dial(ctx, endpoint, &websocket.DialOptions{HTTPHeader: http.Header{"Authorization": []string{"Bearer " + identity}}})
	if err != nil {
		if response != nil {
			t.Fatalf("dial %s: %v (status=%d)", identity, err, response.StatusCode)
		}
		t.Fatalf("dial %s: %v", identity, err)
	}
	return conn
}

func readYJSMessage(t testing.TB, conn *websocket.Conn) []byte {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	messageType, data, err := conn.Read(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if messageType != websocket.MessageBinary {
		t.Fatalf("message type = %v", messageType)
	}
	return data
}

func waitForYJSAwarenessRemoval(t testing.TB, room *YJSRoom, clientID uint64) {
	t.Helper()
	deadline := time.Now().Add(time.Second)
	for {
		room.mu.Lock()
		_, exists := room.awareness[clientID]
		room.mu.Unlock()
		if !exists {
			return
		}
		if time.Now().After(deadline) {
			t.Fatalf("awareness client %d remained after disconnect", clientID)
		}
		time.Sleep(time.Millisecond)
	}
}

type testSemanticYJSStore struct {
	mu           sync.Mutex
	vector       []byte
	delta        []byte
	document     YJSDocument
	update       []byte
	remoteVector []byte
}

func (store *testSemanticYJSStore) Apply(_ context.Context, document YJSDocument, update []byte) (YJSApplyResult, error) {
	store.mu.Lock()
	defer store.mu.Unlock()
	store.document = document
	store.update = append([]byte(nil), update...)
	return YJSApplyResult{Applied: true, Cursor: 1, StateVector: append([]byte(nil), store.vector...)}, nil
}

func (store *testSemanticYJSStore) StateVector(_ context.Context, document YJSDocument) ([]byte, error) {
	store.mu.Lock()
	defer store.mu.Unlock()
	store.document = document
	return append([]byte(nil), store.vector...), nil
}

func (store *testSemanticYJSStore) Diff(_ context.Context, document YJSDocument, remoteVector []byte) ([]byte, error) {
	store.mu.Lock()
	defer store.mu.Unlock()
	store.document = document
	store.remoteVector = append([]byte(nil), remoteVector...)
	return append([]byte(nil), store.delta...), nil
}

func (store *testSemanticYJSStore) Snapshot(context.Context, YJSDocument) (YJSSnapshot, error) {
	return YJSSnapshot{}, ErrYJSStoreUnavailable
}

func (store *testSemanticYJSStore) Merge(context.Context, YJSDocument, [][]byte) ([]byte, error) {
	return nil, ErrYJSStoreUnavailable
}
