// Command typeidgen generates the language-specific CRDT TypeID registries
// from docs/protocol/type-ids.json.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

const (
	specPath       = "docs/protocol/type-ids.json"
	goOutputPath   = "type_ids_generated.go"
	tsOutputPath   = "clients/typescript/src/type_ids.generated.ts"
	generatedGoPkg = "crdt"
)

type registry struct {
	FormatVersion uint64      `json:"format_version"`
	FrameTypes    []frameType `json:"frame_types"`
}

type frameType struct {
	Name             string `json:"name"`
	StateID          uint64 `json:"state_id"`
	DeltaID          uint64 `json:"delta_id"`
	SemanticsVersion uint64 `json:"semantics_version"`
	UsesHLC          bool   `json:"uses_hlc"`
}

func main() {
	check := flag.Bool("check", false, "verify generated files are current")
	flag.Parse()
	if flag.NArg() != 0 {
		failf("unexpected arguments: %s", strings.Join(flag.Args(), " "))
	}

	input, err := os.ReadFile(specPath)
	if err != nil {
		failf("read %s: %v", specPath, err)
	}
	var value registry
	if err := json.Unmarshal(input, &value); err != nil {
		failf("decode %s: %v", specPath, err)
	}
	if err := value.validate(); err != nil {
		failf("validate %s: %v", specPath, err)
	}

	outputs := map[string][]byte{
		goOutputPath: renderGo(value),
		tsOutputPath: renderTypeScript(value),
	}
	paths := make([]string, 0, len(outputs))
	for path := range outputs {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		if *check {
			if err := verify(path, outputs[path]); err != nil {
				failf("%v", err)
			}
			continue
		}
		// #nosec G306 -- generated source files are intentionally world-readable.
		if err := os.WriteFile(path, outputs[path], 0o644); err != nil {
			failf("write %s: %v", path, err)
		}
	}
}

func (r registry) validate() error {
	if r.FormatVersion != 1 {
		return fmt.Errorf("format_version = %d, want 1", r.FormatVersion)
	}
	if len(r.FrameTypes) == 0 {
		return errors.New("frame_types is empty")
	}
	usedIDs := make(map[uint64]string, len(r.FrameTypes)*2)
	usedNames := make(map[string]struct{}, len(r.FrameTypes))
	for _, frame := range r.FrameTypes {
		if !validName(frame.Name) {
			return fmt.Errorf("invalid frame type name %q", frame.Name)
		}
		if _, exists := usedNames[frame.Name]; exists {
			return fmt.Errorf("duplicate frame type name %q", frame.Name)
		}
		usedNames[frame.Name] = struct{}{}
		if frame.StateID == 0 || frame.DeltaID == 0 || frame.StateID == frame.DeltaID {
			return fmt.Errorf("%s has invalid state/delta IDs %d/%d", frame.Name, frame.StateID, frame.DeltaID)
		}
		if frame.SemanticsVersion == 0 {
			return fmt.Errorf("%s has zero semantics_version", frame.Name)
		}
		for _, entry := range []struct {
			id   uint64
			kind string
		}{{frame.StateID, "state"}, {frame.DeltaID, "delta"}} {
			if previous, exists := usedIDs[entry.id]; exists {
				return fmt.Errorf("TypeID %d is used by both %s and %s %s", entry.id, previous, frame.Name, entry.kind)
			}
			usedIDs[entry.id] = frame.Name + " " + entry.kind
		}
	}
	return nil
}

func validName(value string) bool {
	if value == "" || !unicode.IsUpper(rune(value[0])) {
		return false
	}
	for _, value := range value {
		if !unicode.IsLetter(value) && !unicode.IsDigit(value) {
			return false
		}
	}
	return true
}

func renderGo(r registry) []byte {
	var output bytes.Buffer
	output.WriteString("// Code generated by internal/cmd/typeidgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "package %s\n\n", generatedGoPkg)
	output.WriteString("// Stable frame type assignments. Values are part of the v1 wire contract and\n")
	output.WriteString("// must never be reused for a different payload shape. The source of truth is\n")
	output.WriteString("// docs/protocol/type-ids.json.\n")
	output.WriteString("const (\n")
	for _, frame := range r.FrameTypes {
		fmt.Fprintf(&output, "\tTypeID%sState uint64 = %d\n", frame.Name, frame.StateID)
		fmt.Fprintf(&output, "\tTypeID%sDelta uint64 = %d\n", frame.Name, frame.DeltaID)
		fmt.Fprintf(&output, "\tSemanticsVersion%s uint64 = %d\n", frame.Name, frame.SemanticsVersion)
	}
	output.WriteString(")\n\n")
	output.WriteString("var frameTypeRegistrations = [...]FrameTypeRegistration{\n")
	for _, frame := range r.FrameTypes {
		fmt.Fprintf(&output, "\t{Name: %q, FrameType: FrameType{StateID: TypeID%sState, DeltaID: TypeID%sDelta, SemanticsVersion: SemanticsVersion%s", frame.Name, frame.Name, frame.Name, frame.Name)
		if frame.UsesHLC {
			output.WriteString(", UsesHLC: true")
		}
		output.WriteString("}},\n")
	}
	output.WriteString("}\n")
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		panic(fmt.Sprintf("format generated Go source: %v", err))
	}
	return formatted
}

func renderTypeScript(r registry) []byte {
	var output bytes.Buffer
	output.WriteString("// Generated from docs/protocol/type-ids.json by internal/cmd/typeidgen; DO NOT EDIT.\n\n")
	output.WriteString("export const FrameType = {\n")
	for _, frame := range r.FrameTypes {
		fmt.Fprintf(&output, "  %sState: %dn,\n", frame.Name, frame.StateID)
		fmt.Fprintf(&output, "  %sDelta: %dn,\n", frame.Name, frame.DeltaID)
	}
	output.WriteString("} as const;\n\n")
	output.WriteString("export const FrameSemanticsVersion = {\n")
	for _, frame := range r.FrameTypes {
		fmt.Fprintf(&output, "  %s: %dn,\n", frame.Name, frame.SemanticsVersion)
	}
	output.WriteString("} as const;\n")
	return output.Bytes()
}

func verify(path string, want []byte) error {
	// #nosec G304 -- paths are fixed generator outputs, not user input.
	got, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read generated file %s: %w", path, err)
	}
	if !bytes.Equal(got, want) {
		return fmt.Errorf("generated file %s is stale; run go generate ./", filepath.Clean(path))
	}
	return nil
}

func failf(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, "typeidgen: "+format+"\n", arguments...)
	os.Exit(1)
}
